### ISSUE TITLE
Tooltips on fav button break when not hovering them after click

### ISSUE THREAD

**Issue by LucileDT** [LucileDT/boustigraille#162]
**Scenario:**
- connect
- go to the recipes list
- click on a fav button and quickly move your cursor away from it
- after 1-2 seconds, hover it again

**Expected behavior:**
The tooltip is showing, with its corresponding text

**Current behavior:**
The tooltip do not show, the HTML attribute title does show. There is an error in the JS console:
```
Uncaught TypeError: can't access property "template", this._config is null
```

**Comment by LucileDT** [comment]
This seems to have been fixed by upgrading the front stack, @Yann-BUTSCHER-EIRL can you confirmed it's fixed?

**Comment by Yann-BUTSCHER-EIRL** [comment]
It's not fixed. The error I get is the following:
![image](https://github.com/user-attachments/assets/43633e18-bcb2-4694-808c-200f316522ed)

**Comment by Yann-BUTSCHER-EIRL** [comment]
@LucileDT @V-Tommy it is fixed and need testing
